# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: d1b298ef0044f24a872e728902efd9bcea14c4f02ed81775329f498bb67ffbf30dcdbead65d36c90c5fb0dbe84947248e4ee314a6fbd381a625fe509062855d4

test:
  domain_name: example.com 
  secret_key_base: 39598cc8a4f79bb24fb79d2ff5ccde0a1d3560212569e621fb3154ebc5268821ec1ba70ae0a617e9cfcd8b493ff32c3f76884b00c13a26a23cafc836b443de64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
